version: '3.8'

services:
  node:
    build: .
    container_name: bsv_fork_node
    volumes:
      - blockchain_data:/root/.bitcoin
    ports:
      - "8333:8333"  # P2P port
      - "8332:8332"  # RPC port
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G
    environment:
      - BITCOIN_RPC_USER=bsvuser
      - BITCOIN_RPC_PASSWORD=bsvpassword
    command: ["./src/bitcoind", "-printtoconsole"]

volumes:
  blockchain_data:
    driver: local
